spring:
  datasource:
    url: jdbc:mysql://datasource:3306/topolevsky?useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: New_password_1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (validate, create, create-drop, update)
      ddl-auto: update
      # Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: "*"
